### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEE#358]
**Is your feature request related to a problem? Please describe.**
At the moment, downsampling is disabled in default panel settings, and must be enabled in each panel individually during the app preconfiguration.

**Describe the solution you'd like**
Allow the user to set (and examine) a variety of global options which affect the way in which the various panel constructors initialize the default settings.
Essentially a wrapper around `?options`.
In addition to downsampling, this could also be used to set a different default value for other fields, e.g.:
- `.organizationHeight`
- `.organizationWidth`
- `.selectParamBoxOpen`
- `.dataParamBoxOpen`
- `.colorByDefaultColor`
- `.selectColor`
- `.selectTransAlpha`
- `.visualParamBoxOpen`
- `.contourAdd`
- `.contourColor`
- `.plotPointSize`
- `.plotPointAlpha`
- `.plotPointDownsample`
- `.plotPointSampleRes`
- `.plotFontSize`
- `.plotLegendPosition`

Essentially, any field that does not depend on the contents of `se`.

**Describe alternatives you've considered**
Modes can address this to some extent.

**Additional context**
n/a

**Comment by LTLA** [comment]
It is best that this has its effect during `Panel` construction, so as to ensure that people trying to reproduce app state do not have to worry about setting or unsetting the global parameters.
