### ISSUE TITLE
Increase the size of points in legend

### ISSUE THREAD

**Issue by kikegoni** [iSEE/iSEE#427]
Hey,

Thanks a lot for developing the package, I really consider it super useful.

I was just wondering if there is a way to increase the size of points in the legend without modifying their size in the ggplot panel. 

This has been asked for doing that in ggplot2 [here](https://stackoverflow.com/questions/20415963/how-to-increase-the-size-of-points-in-legend-of-ggplot2), so I is basically adding this line to the ggplot:

```r
+ guides(colour = guide_legend(override.aes = list(size=10)))
```

Thanks in advance for any insight you might have. 

Best,

Kike

**Comment by kevinrue** [comment]
Dear @kikegoni 

Thanks for the suggestion.
Indeed that shouldn't be an issue, it's just about adding a UI element, an observer, and a command to the `DotPlot` class.

I'll send another message here when done.

Best
Kevin

**Comment by kevinrue** [comment]
The feature in implemented on this branch: https://github.com/iSEE/iSEE/tree/legend

It just needs a few unit tests before being released.

In the meantime if you want to try it out, you'll have to install it from github:

```r
BiocManager::install("iSEE/iSEE", ref = "legend")
```

**Comment by kevinrue** [comment]
Fixed by #428

**Comment by kikegoni** [comment]
Hey @kevinrue ,

Thanks for your answer. 

It is not installed yet in the master branch right?

I am getting and error saying it is not possible to open the the URL of the legend branch, both with BiocManager (your command above) and with devtools:

```r
devtools::install_github("iSEE/iSEE",ref = "legend")
Downloading GitHub repo iSEE/iSEE@legend
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/iSEE/iSEE/tarball/legend'
```

Don't know if that's in my side because when I try to access https://github.com/iSEE/iSEE/tree/legend I says the URL does not exist.

Best,

Kike

**Comment by kevinrue** [comment]
Hi

Sorry I should have clarified. My "fixed" message above referred to the fact that it is now merged to the `master` branch (on GitHub) and available from the devel branch (on Bioconductor 3.12).
As such , the `legend` branch does not exist anymore as it was merged to master.

In other words, you should get the updated version 2.1.7 of iSEE using either of the following two commands:

```
devtools::install_github("iSEE/iSEE")
BiocManager::install("iSEE", version = "3.12")
```

**Comment by kikegoni** [comment]
Hey @kevinrue ,

Thanks for the explanation and the fix, I can confirm it is working now.

Anyway, maybe I just noticed a bug, this is working correctly when the class of the data we are plotting is categorical, so the dot size for each category can now be modified. However, when the data is continuous, such us the gene counts this should not be changed and the legend should still be the scale bar. am I right?

Best,

Kike

**Comment by kevinrue** [comment]
I did not check that. Thanks for reporting the issue.

In the future perhaps you could provide reproducible code and perhaps a screenshot to illustrate your issue and facilitate our conversation.

Here is what I've used
```r
library(scRNAseq)

# Example data ----
sce <- ReprocessedAllenData(assays="tophat_counts")
class(sce)

library(scater)
sce <- logNormCounts(sce, exprs_values="tophat_counts")

sce <- runPCA(sce, ncomponents=4)
sce <- runTSNE(sce)
rowData(sce)$ave_count <- rowMeans(assay(sce, "tophat_counts"))
rowData(sce)$n_cells <- rowSums(assay(sce, "tophat_counts") > 0)
sce

# launch the app itself ----

iSEE(sce, initial = list(ReducedDimensionPlot(
  ColorBy = "Column data",
  ColorByColumnData = "NREADS",
  LegendPointSize = 2
)))

```

**Comment by kevinrue** [comment]
Also I realise that my fix was specific to scatter plots. Violin plots and Hinton plots still have the original issue.

**Comment by kevinrue** [comment]
Updated MWE for checking progress on the feature 

```r
library(scRNAseq)

# Example data ----
sce <- ReprocessedAllenData(assays="tophat_counts")
class(sce)

library(scater)
sce <- logNormCounts(sce, exprs_values="tophat_counts")

sce <- runPCA(sce, ncomponents=4)
sce <- runTSNE(sce)
rowData(sce)$ave_count <- rowMeans(assay(sce, "tophat_counts"))
rowData(sce)$n_cells <- rowSums(assay(sce, "tophat_counts") > 0)
sce

# launch the app itself ----

iSEEOptions$set(legend.point.size = 2)

iSEE(sce, initial = list(
  ReducedDimensionPlot(ColorBy = "Column data", ColorByColumnData = "NREADS", VisualChoices = c("Color", "Text")),
  ColumnDataPlot(ColorBy = "Column data", ColorByColumnData = "NREADS", VisualChoices = c("Color", "Text")),
  ColumnDataPlot(XAxis = "Column data", XAxisColumnData = "passes_qc_checks_s", YAxis = "driver_1_s", ColorBy = "Column data", ColorByColumnData = "NREADS", VisualChoices = c("Color", "Text")),
  ReducedDimensionPlot(ColorBy = "Column data", ColorByColumnData = "driver_1_s", VisualChoices = c("Color", "Text"), LegendPointSize = 1),
  ReducedDimensionPlot(ColorBy = "Column data", ColorByColumnData = "driver_1_s", VisualChoices = c("Color", "Text"), LegendPointSize = 2),
  ReducedDimensionPlot(ColorBy = "Column data", ColorByColumnData = "driver_1_s", VisualChoices = c("Color", "Text"), LegendPointSize = 3)
))
```

**Comment by kikegoni** [comment]
Hey @kevinrue ,

Thanks a lot for fixing this. I can confirm now that is working perfectly. Sure, I'll follow your advice for the future.

Best,

Kike
