### ISSUE TITLE
[BUG] ComplexHeatmapPlot doesn't have an .exportOutput method

### ISSUE THREAD

**Issue by LTLA** [iSEE/iSEE#437]
Try exporting a complex heatmap plot by itself, it'll fail.

On a related note, the ComplexHeatmapPlot doesn't document its methods.

**Comment by kevinrue** [comment]
#444 adds the .exportOutput` method

If anyone's impatient, the PR is ready for merge.
Otherwise, wait and I'll throw in the updated documentation for `ComplexHeatmapPlot`

**Comment by kevinrue** [comment]
Fixed by #444

**Comment by kevinrue** [comment]
#450 fixes a missed spot
