### ISSUE TITLE
.defineOutput: unused argument in DotPlot definition

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEE#445]
`id` is not used in the function definition below

```r
#' @export
setMethod(".defineOutput", "DotPlot", function(x, id) {
    plot_name <- .getEncodedName(x)
    col <- .getPanelColor(x)

    .define_plot_ui(plot_name, brush_direction="xy",
        height=x[[.organizationHeight]],
        brush_fill=.lighten_color_for_fill(col),
        brush_stroke=col
    )
})
```

Functions call don't seem to use the `id` argument either:

```
R/interface_panel.R:            list(.defineOutput(instance), param),
```

This also needs to be fixed in the documentation, i.e. `id` needs to be removed.

Also apply the fix to the `Table` class.

**Comment by LTLA** [comment]
Probably a leftover from the time that we were passing panel names and IDs. Double-check **iSEEu** to see if anything wacky is happening there, but otherwise I'm happy to see it purged.
