### ISSUE TITLE
[BUG] HiddenColumns is not Table-wide and so fails for Table subclasses.

### ISSUE THREAD

**Issue by LTLA** [iSEE/iSEE#464]
Table subclasses call `.create_table_output()` but this assumes that the `HiddenColumns` slot exist... which it may not, as its presence is only guaranteed for `RowDataTable`s and `ColumnDataTable`s.

One solution is to move `HiddenColumns` as a `Table`-wide generic. However, this philosophically requires us to move the UI elements and observers to that for the `Table`... and the UI element's defaults won't make a lot of sense because we don't, in general, know the set of available columns for an arbitrary `Table` before its creation.

We may have to `updateSelectInput()` WITHIN the `renderDataTable()`, as the latter is the only point at which the table's column names become available. This would... not be entirely appropriate, but we do also let information leak out when rendering `allPanels`, so I guess it's not entirely without precedent.

**Comment by kevinrue** [comment]
Indeed. I noticed this morning that it broke my prototype https://github.com/kevinrue/iSEEClusterProfiler/tree/table 😢 

i.e. another fix somewhere on my radar

**Comment by LTLA** [comment]
I'll handle this one, but #456 is yours. Or you could add to #463.
