### ISSUE TITLE
Rename some internal variables

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEE#468]
```r
.selectColDynamic
.selectColSaved
.selectColSource
.selectColType
```

Expand "Col" to Column

**Comment by federicomarini** [comment]
while at it, also `.selectColRestrict`, I guess?

**Comment by federicomarini** [comment]
Commenting as going through it, `.selectColSaved` and `.selectColType` went away already.
Addressing this in `col_2_column`...
