### ISSUE TITLE
pure shiny app for iSEE

### ISSUE THREAD

**Issue by tamuanand** [iSEE/iSEE#516]
Hi @federicomarini 

Thanks for all the wonderful work on pcaExplorer/ideal/iSEE.

Is it possible to have iSEE as a pure shinyapp similar to how you have for ideal/pcaExplorer
- https://github.com/federicomarini/ideal_serveredition
- https://github.com/federicomarini/pcaExplorer_serveredition

Thanks,

**Comment by LTLA** [comment]
You can just create an `app.R` file with the lines:

```r
library(iSEE)
iSEE()
```

In fact, if you should so desire, you can customize the landing page itself - see `?createLandingPage`.

**Comment by kevinrue** [comment]
I think this issue is answered.
