### ISSUE TITLE
Document .fill_se_dimnames

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEE#527]
Functions or methods with usage in documentation object '.fill_se_dimnames' but not in code:
     ‘.fill_se_dimnames’

**Comment by LTLA** [comment]
This is dead, isn't it? Replaced by the new thing that fixes all names.

**Comment by kevinrue** [comment]
Honestly I haven't checked thoroughly, I just pasted the warning that
popped up when I ran R CMD check.
Oh wait, I haven't roxygenated locally, maybe that's it. My bad!
