### ISSUE TITLE
[Suggestion] link ComplexHeatmapPanel to other panels

### ISSUE THREAD

**Issue by jokergoo** [iSEE/iSEE#546]
iSEE can transmit information (selected rows and columns) between different panels. Currently ComplexHeatmap panel is the end of the transmission (https://github.com/iSEE/iSEE/blob/master/R/observers_heatmap.R#L139) and there is no further actions other panels can play with ComplexHeatmap panel. 

I am currently development a package [InteractiveComplexHeatmap](https://github.com/jokergoo/InteractiveComplexHeatmap) which can convert static complex heatmaps to interactive heatmaps. I've read how to implement new panel in iSEE in the vignettes, but it seems it only supports to output a plot or a table, while InteractiveComplexHeatmap outputs a complex widget, or maybe I was lost in the vignette because there are too much information there :). 

However, there are following functions in InteractiveComplexHeatmap that might be helpful for you to continue the transmission starting from ComplexHeatmap panel to other panels. I think the key thing here is to capture the row indices and column indices when users brush or click on the heatmap.

Basically three functions from InteractiveComplexHeatmap are to be used. First, the positions of all heatmap slices are retrieved by function `htPositionsOnDevice()`. I think in ComplexHeatmap panel in iSEE, there is only one heatmap with no splitting, so here this functions returns the position of the single heatmap body. Note this function should be called inside a `plotOutput` because the heatmap should be generating and `htPositionsOnDevice()` needs to access various viewports to get the positions.

```r
ht_list = draw(ht_list)
ht_pos = htPositionsOnDevice(ht_list)
```

Second, the position of the brush (if users brush on the heatmap) can be obtained by `InteractiveComplexHeatmap:::get_pos_from_brush()`. The argument for this argument is the brush ID on the UI. This function simply returns a list of two `unit` objects, which are the positions of the bottom left and top right of the brush rectangle.

```r
lt = InteractiveComplexHeatmap:::get_pos_from_brush(input$heatmap_brush_id)
pos1 = lt[[1]]
pos2 = lt[[2]]
```

Last, send the brush position and heatmap position to function `selectArea()`. There are several arguments there:

- `ht_list`: the heatmap object. Because the rows and columns might be reordered due to clustering, the reordering informationn is stored in the heatmap object.
- `mark`: always set to `FALSE`.
- `pos1` and `pos2`: position of the brush.
- `verbose` set to `FALSE` to turn off messages.
- `ht_pos`: position of the heatmap.

```r
df_brush = selectArea(ht_list, mark = FALSE, pos1 = pos1, pos2 = pos2, verbose = FALSE, ht_pos = ht_pos)
```

The function returns a  data frame of the row indices and column indices that users selected. An example output is as follows.
In the example, the heatmap is split by k-means and the brush was overlap heatmap slices, so you can see the data frame contains multiple rows and each row corresponds to one row slice and one column slice.

```
## DataFrame with 4 rows and 6 columns
##       heatmap                  slice row_slice column_slice     row_index
##   <character>            <character> <numeric>    <numeric> <IntegerList>
## 1       mat_a mat_a_heatmap_body_1_2         1            2     7,5,2,...
## 2       mat_a mat_a_heatmap_body_2_2         2            2           6,3
## 3       mat_b mat_b_heatmap_body_1_1         1            1     7,5,2,...
## 4       mat_b mat_b_heatmap_body_2_1         2            1           6,3
##    column_index
##   <IntegerList>
## 1     2,4,1,...
## 2     2,4,1,...
## 3     1,2,3,...
## 4     1,2,3,...
```

It is similar to capture the row/column index for the single cell that user clicked (or hovered/double clicked). Just change to the functions `InteractiveComplexHeatmap:::get_pos_from_click()` and `selectPosition()`.

```r
pos1 = InteractiveComplexHeatmap:::get_pos_from_click(input$heatmap_click_id)
df_click = selectPosition(ht_list, mark = FALSE, pos = pos1, verbose = FALSE, ht_pos = ht_pos)
```

The returned object `df_click` always have one row if a cell was clicked.

```
## DataFrame with 1 row and 6 columns
##       heatmap                  slice row_slice column_slice row_index
##   <character>            <character> <numeric>    <numeric> <integer>
## 1       mat_a mat_a_heatmap_body_1_2         1            2         4
##   column_index
##      <integer>
## 1            2
```

If users didn't brush or click into the heatmap, `selectArea()` and `selectPosition()` return `NULL`.

Then, I guess the captured row indices and column indices can be sent to other panels.

Hope it helps!

**Comment by LTLA** [comment]
Without looking too much into **InteractiveComplexHeatmap**, the biggest conceptual question is: what would the panel transmit? A row selection? Or a column selection? **iSEE** only expects one or the other for a given panel class.

There are also some technical questions that need to be resolved. For example, *iSEE* doesn't provide downstream panels with access to `input` during rendering of the `output`, as any changes to `input` must go through the Panel classes to ensure that we have the application state captured at all times. If you need to use functions that depend on `input` and `output` being simultaneously available... there won't be anywhere to run that function inside **iSEE**.

**Comment by jokergoo** [comment]
As I have shown previously, the function `selectArea()` returns a data frame that contains both row indices and column indices, so imagine when you select an area from the heatmap, all row panels change correspondingly to the row selection and at the same time all column panels change correspondingly to the column selection. Maybe it is not a good idea that selecting on heatmap changes all other panels, but this is just an idea.

There is one place where `input` needs to be used is to retrieve the brush information. If it is impossible to directly get `input` under iSEE framework, then maybe it is not easy to implement my proposal.

**Comment by LTLA** [comment]
> all row panels change correspondingly to the row selection and at the same time all column panels change correspondingly to the column selection

That's what I'm trying to say - you need to pick one or the other, you can't have both. Currently, **iSEE** doesn't understand the concept of a panel transmitting selections on _both_ the rows and columns. I suppose we could refactor it, but that would be a moderate amount of effort, so any immediate approach would need to pick a side.

> There is one place where `input` needs to be used is to retrieve the brush information. If it is impossible to directly get `input` under iSEE framework, then maybe it is not easy to implement my proposal.

To be clear, the restriction is that you cannot use `input` _and_ `output` at the same time. Any changes to the brush must be stored in the Panel class instance (in an observer in `.createObservers()`) before being used in `.renderOutput()`.

**Comment by jokergoo** [comment]
OK, thanks!

**Comment by LTLA** [comment]
@kevinrue and I would be interested to see a PR of how such a panel might work.

**Comment by kevinrue** [comment]
The heatmap has always been a challenging panel with regard to selection and needs proper time to consider the best (i.e. sustainable) way forward.

Historically, we initially used `ggplot2::geom_raster()` (https://github.com/iSEE/iSEE/blob/57da6aa33b149340801d4d5c122167cdd43fd69d/R/heatmap.R#L156) to stick with the ggplot2 framework, but switched over to `ComplexHeatmap` to handle column and row annotations more easily, at the cost of moving out of the `shiny` point selection framework.

Anyway, I can't promise an immediate time when I can dedicate time to this, but it is something that on the back of my mind as a general improvement.

As a side note, I don't see a reason why panels couldn't have two generic 'selection slots' one for rows another for columns, with certains panels unable to fill one or the other (i.e., leaving it `NULL`). I'd have to look into the details of our current implementation to comment further, I haven't been in that part of the code for a while.

**Comment by LTLA** [comment]
> As a side note, I don't see a reason why panels couldn't have two generic 'selection slots' one for rows another for columns

Oh, we can. We just can't _transmit_ on both.
