### ISSUE TITLE
Avoid `if` statement in code tracker

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEE#557]
https://github.com/iSEE/iSEE/blob/7b20d42f527c50c771e6be1c925dbdd54f707bd6/R/outputs_heatmap.R#L204

The value of `is.null(names(.col_colors))` should probably be evaluated internally at this point to decide a bit of code that doesn't include an `if` statement in the code tracker

**Comment by csoneson** [comment]
Keep as-is - it was introduced to fix #549
