### ISSUE TITLE
Custom Additional information

### ISSUE THREAD

**Issue by tanyasg** [iSEE/iSEE#570]
Use case: I would like to create a glossary of terms used in my sample metadata and have it incorporated in the app itself via Additional information.

**Describe the solution you'd like**
Have the ability to create a custom button in Additional information that links to my glossary of terms. A pop up like the current "About this session" or "About iSEE" would work. Having the ability to link to an external page instead of a pop up would be nice too.

**Additional context**
![image](https://user-images.githubusercontent.com/25040762/129940937-240f4bdd-8874-42bc-9c68-d45803837784.png)

**Comment by kevinrue** [comment]
Thank you for the suggestion. I'm overloaded at the moment, but it sounds like a great idea that I look forward to implement at the next opportunity!

**Comment by federicomarini** [comment]
Thinking out loud for how it would make most sense to realize this

Would a single markdown file contain all the formatting needs? Could become an additional parameter when launching iSEE
----> no md -> no button; md is there -> button is there to open up the `includeMarkdown`ed version of it (if it is a modal)

I was thinking about a similar functionality but centered around the `metadata` slot of a SummarizedExperiment, especially if provided as a MIAME-like class. That could also be rendered in an interactive way with some tiny widget (or well as simple text as well)?

**Comment by LTLA** [comment]
In the meantime, you could consider chucking the glossary into `iSEEu:MarkdownBoard`. A bit more visible than having it tucked away into a dropdown, which tends to be a bit unwieldy anyway (the modals and friends will mask the app, so people trying to look at the app and the glossary at the same time will have a tough time).

**Comment by kevinrue** [comment]
The tour could be used to link to a web page and the markdown board can be used in-app.

Thanks for the suggestion, but we'll close this unless there is more demand for this
