### ISSUE TITLE
extensible distance functions and/or add YS1 measure to standard list

### ISSUE THREAD

**Issue by malcook** [iSEE/iSEE#571]
**Is your feature request related to a problem? Please describe.**
I want to be able to declare new distance functions and make them make appear in the  UI

**Describe the solution you'd like**

**Additional context**
Specifically I hope to incorporate Son and Baek dissimilarities YS1 and YR1 as defined (in python) in https://github.com/GuyTeichman/pairwisedist  (and importable via reticulate)

**Comment by kevinrue** [comment]
I guess that could be feasible, as long as all distance functions use the same interface of inputs and outputs.
Then, there is also the discussion of which dependency would provide those additional distance functions.

**Comment by malcook** [comment]
Might you consider adopting the interface provided by [proxy](https://cran.r-project.org/web/packages/proxy/index.html)  which "Provides an extensible framework for the efficient calculation of auto- and cross-proximities, along with implementations of the most popular ones." - then the iSEE developer could register a a novel distance function in their `initial.R` which could be picked up by iSEE's gui builder.

**Comment by kevinrue** [comment]
Thanks for the pointer. I hadn't heard of that package before. Without looking at in in any depth, I'd say that it's always a possibility. However, I'm overloaded this month and can't look at it for now I'm afraid :/

**Comment by malcook** [comment]
> However, I'm overloaded this month and can't look at it for now I'm afraid

Understood, and I appreciate iSEE as it stands.  

I took a tour of iSEE source code to see how hard it might be for me to add it and came away unsure of whether it was within my reach.  

As a "workaround", I thought there might be a clever way to override the definition of one of the in-built measures, such as Kendall, but was unable to figure out how to do even that.

If you see a quick way for me to "fool" iSEE into applying an alternate distance function, I would be obliged.

**Comment by kevinrue** [comment]
Closing this as there is no immediate plan to implement it. Feel free to reopen if there still is a need.

Note the possibility of developing an extension package with a dedicate panel.
