### ISSUE TITLE
Option to for user to dynamically change SummarizedExperiment chosen from serverSide collection of them

### ISSUE THREAD

**Issue by malcook** [iSEE/iSEE#572]
**Is your feature request related to a problem? Please describe.**

As a bioinformatician on a multi-omics experiment (yielding multiple summarized experiments: ATAC-Seq, various ChIP-Seq, RNA-Seq) , I would like to provide my colleagues with one stop shopping for running iSEE and choosing from among a directory full of .RDS files.

**Describe the solution you'd like**
argument of paths to multiple serverSide SummarizedExperiments popuates a select dropdown allowing switching between SEs

**Describe alternatives you've considered**
create an app.R which loades the SE from the first RDS file in the same directory it finds.
put each distinct omic.RDS file in a separate subdirectory within shinyApps, along with a symlink to the app.R 

**Additional context**
This is sort of like #299 / #300 (for which kudos on heroic efforts), except serverSide.

**Comment by LTLA** [comment]
Did you have a look at the `createLandingPage` examples? This allows you to create an arbitrary Shiny loading page that will then launch the app itself for any arbitrary `SummarizedExperiment` (plus `Panel` configuration).

**Comment by malcook** [comment]
thanks @LTLA  - that capability precisely addresses my needs - excellent.
