### ISSUE TITLE
Development of single "feature" transmitting panel class

### ISSUE THREAD

**Issue by vondoRishi** [iSEE/iSEE#574]
**Is your feature request related to a problem? Please describe.**
The **RowDataTable** takes lots of space when there are not enough data to show except gene symbols. The "search" is also case-sensitive which is not helpful for the user. 

**Describe the solution you'd like**
I am trying to make a replacement of **RowDataTable** with a new panel **EasyGeneSearch**. In this panel, the user will be able to search his/her gene of interest from a "drop-down" and the selected gene can be transmitted to multiple panels like ReducedDimensionPlot, FeatureAssayPlot, and others.

**Describe alternatives you've considered**
I have made **RowDataTable** search case-insensitive. However, a simple "drop-down" would be better in some cases.

**Additional context**
I have tried to follow chapter 8 from [iSEE-book](https://isee.github.io/iSEE-book) and [Generics for controlling single selections](https://isee.github.io/iSEE/reference/single-select-generics.html).  However, it is not transmitting the gene from **EasyGeneSearch**.
Here is a screenshot 
![Screenshot from 2021-11-25 15-13-42](https://user-images.githubusercontent.com/6110508/143450754-0fe7fbbd-3326-4902-aa2a-ac3e3df5f4a5.png)

The sample code is here

```{r }
library(iSEE)
library(S4Vectors)
setClass("EasyGeneSearch",
         contains = "Panel",
         slots = c(GeneNames = "character")) ## GeneNames for displaying gene names

setMethod("initialize", "EasyGeneSearch",
          function(.Object, GeneNames="", ...)
          {
              callNextMethod(.Object, GeneNames=GeneNames, ...)
          })

EasyGeneSearch <- function(GeneNames=c(),...){
    new("EasyGeneSearch",GeneNames,...)
}

setMethod(".fullName", "EasyGeneSearch", function(x) "Easy Gene Search")

setMethod(".panelColor", "EasyGeneSearch", function(x) "#BB00FF")

setMethod(".defineInterface", "EasyGeneSearch", function(x, se, select_info) {
    return(shinyjs::hidden(callNextMethod()))
})

setMethod(".defineOutput", "EasyGeneSearch", function(x,...) {
    # cmds <- callNextMethod()
    plot_name <- .getEncodedName(x)
    a <- tagList(selectizeInput(paste0(plot_name, "_", "GeneNames"),label= "Select a gene",
                                choices=list()))
    return(a)
})

setMethod(".createObservers", "EasyGeneSearch", function(x, se, input, session, pObjects, rObjects) {
    callNextMethod()
    panel_name <- .getEncodedName(x)
    .createUnprotectedParameterObservers(panel_name,
                                         fields=c("GeneNames"),
                                         input=input, pObjects=pObjects, rObjects=rObjects)
    geneNameParam <- paste0(panel_name, "_", "GeneNames")
    updateSelectizeInput(session, geneNameParam, server=TRUE,
                         choices=x[["GeneNames"]],selected = x[["GeneNames"]][1] )
    
    observeEvent(input[[geneNameParam]], {
        pObjects$memory[[panel_name]][["GeneNames"]] <- input[[geneNameParam]]
        .requestActiveSelectionUpdate(panel_name, session, pObjects, rObjects, update_output=FALSE)
    }, ignoreInit=TRUE, ignoreNULL=FALSE)
    invisible(NULL)
})

setMethod(".singleSelectionDimension", "EasyGeneSearch", function(x) "feature")

setMethod(".singleSelectionValue", "EasyGeneSearch", function(x) { #, contents
    slot(x, "GeneNames")
})


# setMethod(".singleSelectionSlots", "EasyGeneSearch", function(x) {
#     c(callNextMethod(),
#       list(
#           list(
#               parameter="GeneNames",
#               source="GeneNames",
#               dimension="feature",
#               use_mode="GeneNames",
#               use_value="GeneNames",
#               # dynamic=.colorByFeatDynamic,
#               protected=TRUE
#           )
#       )
#     )
# })
```

```{r }
se1 <- SummarizedExperiment(assays = list(count=matrix(rnorm(1000,mean = 10,sd=2), ncol = 10)))
colnames(se1) <- paste("Sample",c(rep("A",5),rep("B",5)))
rownames(se1) <- paste("Gene",1:100)
colData(se1) <- DataFrame(Treatment=c(rep("A",5),rep("B",5)))
se1
```

```{r}
geneData <- rowData(se1 )
geneNames <- rownames(geneData)
names(geneNames) <- geneNames

rex <- EasyGeneSearch( GeneNames = geneNames)

fex <-FeatureAssayPlot(VisualChoices=c("Other"),PanelWidth=6L)
fex[["ColorByColumnData"]] = "Treatment"
fex[["XAxisColumnData"]] = "Treatment"
fex[["XAxis"]] = "Column data"
fex[["ColorBy"]] = "Column data"
fex[["YAxisFeatureSource"]] = "EasyGeneSearch1"


iSEE(se1, initial=list(rex, fex))
```

**Comment by kevinrue** [comment]
Thanks for your interest in iSEE ! I'll look into this ASAP (starting with updating all my packages to the latest version and verifying that I can replicate your issue). I'll report here when I have more information.
Best, Kevin

**Comment by kevinrue** [comment]
Are you sure this is the latest version of your code for this panel?
I have just tested it and when I run the last line of your code to launch the app - `iSEE(se1, initial=list(rex, fex))` - I get the error:

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function '.generateOutput' for signature '"EasyGeneSearch"'
```

Indeed, the method is not defined for your panel class:

```
> showMethods(".generateOutput")
Function: .generateOutput (package iSEE)
x="ComplexHeatmapPlot"
x="DotPlot"
x="Table"
```

Which is logical, since your class definition makes it inherit from the virtual class `Panel`, which does not have a definition for this method.

Can you please check again what exact code you ran to yield the screenshot that you posted above?

Best
Kevin

**Comment by vondoRishi** [comment]
Sorry I was using iSEE 2.0.0. I will update to the latest version and will update here very soon.

**Comment by vondoRishi** [comment]
> Are you sure this is the latest version of your code for this panel? I have just tested it and when I run the last line of your code to launch the app - `iSEE(se1, initial=list(rex, fex))` - I get the error:
> 
> ```
> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function '.generateOutput' for signature '"EasyGeneSearch"'
> ```
> 
> Indeed, the method is not defined for your panel class:
> 
> ```
> > showMethods(".generateOutput")
> Function: .generateOutput (package iSEE)
> x="ComplexHeatmapPlot"
> x="DotPlot"
> x="Table"
> ```
> 
> Which is logical, since your class definition makes it inherit from the virtual class `Panel`, which does not have a definition for this method.
> 
> Can you please check again what exact code you ran to yield the screenshot that you posted above?
> 
> Best Kevin

**Comment by vondoRishi** [comment]
I have closed this due to my negligence that I did not use the latest iSEE. However, the problem still exists although I use now 
**RowDataTable** instead of "panel" class in my above code for _setClass_ like this 

```{r}
setClass("EasyGeneSearch",
         contains = "RowDataTable",
         slots = c(GeneNames = "character"))
```

Please reconsider this if it is valid.
