### ISSUE TITLE
More options to landing page

### ISSUE THREAD

**Issue by Goultard59** [iSEE/iSEE#579]
Hello, 

I have a personalised landing using the code below : 

`all.data <- c("embryo_j5", "embryo_j7", "embryo_j9", "embryo_j11")
  lpfun <- iSEE::createLandingPage(
    seUI=function(id) selectInput(id, "Dataset:", choices=all.data),
    seLoad=function(x) get(x)
  )`

But I would like to know if it's possible to add more options available

- I would like to remove the file uploader
- I would like to know if it's possible to add more personalization like a logo or an introduction text.

I also noticed a brief error message before the launching of the dataset: invalid initial state-supplied
and I the console : 

```
Error in readRDS(x$datapath) : bad 'file' argument
Warning in .refineParameters(extra[[idx]], se) :
  no valid y-axis 'rowData' fields for 'RowDataPlot'
Warning in grSoftVersion() :
  unable to load shared object '/usr/local/lib/R/modules//R_X11.so':
  libXt.so.6: cannot open shared object file: No such file or directory
```

Thanks for your help,
Adrien.

**Comment by kevinrue** [comment]
Hello, and first of all thank you for using iSEE.

Your two suggestions sound sensible, and I'm keen to keep this as an open issue until we find the time to address them properly.

As for the warning, that sounds like an issue specific to the system on which you are running R.
I could take guesses, but it would be much more efficient if you could describe how you use iSEE yourself.

Oh well, I'll take a guess. Are you by any chance using R in a Conda installation? I Google'd this issue that reports the same warning: https://github.com/conda/conda/issues/2020

**Comment by Goultard59** [comment]
Hello,

I have created a docker image with the help of golem package and I launch it with `docker run -p 8787:8787 pig_ISEE`
The code can be found here : Goultard59/pig_ISEE

**Comment by kevinrue** [comment]
OK, so the R installation in that docker image probably does not include the file `/usr/local/lib/R/modules//R_X11.so` which is expected by `grSoftVersion()` from the  [grDevices](https://www.rdocumentation.org/packages/grDevices/versions/3.6.2) package.

 I'm not sure exactly when that function is called. iSEE uses fuctions from grDevices, but not that one directly. In any case, it doesn't sound like an issue affecting your use of iSEE, so I'd put that on the back burner unless you experience any issue practical issue (e.g. plot not displaying).

For the UI changes, I'm a bit short on time right now, but I'm considering coming back to spend a bit of time dealing with open issues over the summer.

**Comment by kevinrue** [comment]
Quick follow up, while I revisit open issues.

I've been toying with custom landing pages that do not use `createLandingPage()`.
It takes 'a bit' more brainpower, but you can basically put anything in a custom landing page.

Here are a few examples:
https://github.com/kevinrue/iSEElandingpage

I've also just started converting one of those scripts into a package:
https://github.com/kevinrue/iSEEExperimentHub

I hope that helps. 

In due time, I hope to describe the process of creating those landing pages from scratch, though from those few examples, I can already say that it rapidly becomes app-specific (e.g. tracking of reactive elements and coordination of observers).

**Comment by federicomarini** [comment]
Thank you a damn lot Kevin for putting together the examples.

Indeed, your fantasy is very much the only limit for the landing pages.
I hope to find some more bandwidth and give my hub idea some further refinement sometime soon.

**Comment by kevinrue** [comment]
@Goultard59 

I will close this issue for now, as I consider that my earlier message gives pointers to examples that demonstrate how to personalise the landing page. 

I cannot realistically give a 'full' range of examples, as possibilities are literally endless.

I will try and clean up https://github.com/kevinrue/iSEElandingpage over time, adding screenshots so that visitors have a preview without the need to install R and run the script themselves.

I am also continuing to work on https://github.com/kevinrue/iSEEExperimentHub which is rapidly increasing in complexity, as the rapid development of this prototype has motivated me to put in the work for making it a proper Bioconductor-worthy package itself.

Best wishes
Kevin
