### ISSUE TITLE
Display more info on mouse hover-over

### ISSUE THREAD

**Issue by lee-t** [iSEE/iSEE#600]
**Current Behavior*
On mouse-over of any data plot points, a small box appears showing the row# entry of the point. 
**Suggested changes**
Is there any way to extend this box from individual `colData` fields, which would then give more data for each point.  Ie: for a given scatterplot hovering over a point would show gene name or subject ID which would be read from the SCE. 

**Additional context**
Similar to #57 though not sure what has developed since then.

**Comment by kevinrue** [comment]
Hi,

Thanks for your feedback, always appreciated!

That sounds entirely feasible. I guess it just needs some thought , planning and structure in _how_ it will be implemented.

Thoughts:

- We could display the same information in all panels, or potentially allow each panel to display different pieces/combinations of information. Obviously, the latter is more flexible, but likely requires more work.
- The information shown could also be fixed for the entire runtime of an app (i.e., configured in the launch script and that's it), or we could potentially add UI inputs for users to change the information displayed. Again, the latter is more flexible; but likely requires more work/time.

**Comment by kevinrue** [comment]
OK, so...

- We're currently using the shiny builtin `hoverOpts` that shows rownames/colnames -> https://github.com/iSEE/iSEE/blob/70a793cc867a142deedd6e37131d23c9e4605a78/R/outputs_plot.R#L25
- `shinyBS::bsTooltip` displays the same plot-wide tooltip when hovering anywhere on the plot -> https://ebailey78.github.io/shinyBS/docs/Tooltips_and_Popovers.html#examples
- `shinyWidgets::tooltipOptions` is similar to `shinyBS::bsTooltip` above and only applies to dropdown buttons.
- The sheer amount of javascript code in the `shiny` package that mention `hover` probably explains why no I can't find anyone yet who's gone to re-implement it while allowing a custom message. Perhaps open an issue on the shiny github repo, to see what they say? -> https://github.com/rstudio/shiny/issues

Let me know what you decide.

**Comment by kevinrue** [comment]
OK, so I stand corrected, having dug a bit further into what I thought was a novel idea, I rediscovered that our tooltip code is actually more customised than it looks.

Right now, we do already swap the builtin shiny tooltip for another one with custom settings (mostly to deal with the jittering of points in violin plots). However, we set that tooltip to always display only the rownames of the closest point.

https://github.com/iSEE/iSEE/blob/70a793cc867a142deedd6e37131d23c9e4605a78/R/observers_hover.R#L69

That means that we can potentially tweak the contents of the tooltip. However, that requires a bit of extra infrastructure.
Prototype on the `kra-tooltip` branch -> https://github.com/iSEE/iSEE/tree/kra-tooltip

**Comment by kevinrue** [comment]
I've added the possibility to blanket-apply the same tooltip settings to all panels using `registerAppOptions()`.

```r
## Issue: https://github.com/iSEE/iSEE/issues/600
## YouTube video: n/a
## Script written by Kevin Rue-Albrecht

## For each DotPlot panel
## Add a slot that contains the list of rowData/colData columns
## to display in tooltip.
## Individual panels can display distinct tooltip contents.
## In this demo, do not define an initial state: show all panels.

library(iSEE)

# Data ----

library(scater)
sce <- mockSCE()
sce <- logNormCounts(sce)

rowData(sce)[["dummy_numeric"]] <- rnorm(nrow(sce))

## App ----

sce <- registerAppOptions(sce, tooltip.rowdata = c("dummy_numeric"), tooltip.coldata = c("Treatment", "Cell_Cycle"))

app <- iSEE(sce)
shiny::runApp(app, launch.browser = TRUE)
```

This means that you can now even use a combination of `registerAppOptions()` and panel-specific settings, to define a certain tooltip for all panels, while overriding that custom default at the panel level.

Thoughts:

- I keep asking myself whether it's desirable to allow different tooltips per panel.
- If yes, then I think that user inputs should be added to each panel, allowing users to change the contents of each tooltip from within the app.

**Comment by kevinrue** [comment]
OK, so, to give you an idea of ETA, the main functionality is now implemented on branch `kra-tooltip`. I've also documented the new functionality in the man pages. However, I need to add new sanity checking code to catch and manage errors, e.g. ignore invalid rowData/colData column names to avoid errors. I also need to add unit tests for the new code. I can't predict how long this is all going to take me, between other pressing matters.

If you want to play around with the new functionality, you can install the package from the branch:

```r
devtools::install_github("iSEE/iSEE", ref = "kra-tooltip")
```

I'll come back here to post when I finish polishing all the things I mentioned above and release the new version on Bioconductor. Deal? :)

**Comment by lee-t** [comment]
Done deal! 
Thank you so much for working on this. My current use case might have formatting issues with high floating points but I think its worth trying out. I'll report back when I get this going, we'll be in touch.

**Comment by lee-t** [comment]
Some initial feedback: 

- Specifying tooltips in individual plots does work (as in first example) and using a list of colData names will make the tooltip box display all of those values. However, if you use a list of mixed types, it will default to numeric. Ie `TooltipData = c("Cell_type","Technical_repeat_number")` where "Cell_type" values are chrarcters and "Technical_repeat_number" is numeric, this will output a tooltip box where the all the values are numbers ("Cell_type" returns a number, presumably the position in list). 

- Global tooltip settings `registerAppOptions()` does not seem to work on RowDataPlots or ReducedDimensionPlot. Seems largely dependent on plot type whether or not the option applies.

**Comment by kevinrue** [comment]
Thanks for the feedback (and the beta-testing), that's really helpful to cover cases that I haven't.

Your screenshot looks fine to me, should I see anything wrong in it?

I'll test your scenarios with bugs at the next opportunity. I can picture why that's happening, and I'll need a tiny bit of time to think about how to clean up the code to solve that silly oversight of mine elegantly.

**Comment by lee-t** [comment]
right, so I've gotten the wrong screenshot. Sorry about that, the previous one was fine, because it had 2 character columns.

**Comment by kevinrue** [comment]
OK, so I've just pushed a code fix that addresses both the bug displayingfactors and the propagation of the global setting across all DotPlot panels.

Note that I changed from `registerAppOptions()` to `panelDefaults()` and that the name of the option has changed (different option name for row/column oriented panels)

I need to update the docs, but you can try it with :

```r
## Issue: https://github.com/iSEE/iSEE/issues/600
## YouTube video: n/a
## Script written by Kevin Rue-Albrecht

## For each DotPlot panel
## Add a slot that contains the list of rowData/colData columns
## to display in tooltip.
## Use panelDefaults.

library(iSEE)

# Data ----

library(scater)
sce <- mockSCE()
sce <- logNormCounts(sce)

rowData(sce)[["dummy_numeric"]] <- rnorm(nrow(sce))
rowData(sce)[["dummy_character"]] <- sample(LETTERS, nrow(sce), replace = TRUE)
rowData(sce)[["dummy_factor"]] <- factor(sample(letters, nrow(sce), replace = TRUE))

colData(sce)[["Mutation_Status"]] <- factor(colData(sce)[["Mutation_Status"]])

## App ----

panelDefaults(
    TooltipRowData = c("dummy_numeric", "dummy_character", "dummy_factor"),
    TooltipColumnData = c("Treatment", "sizeFactor", "Mutation_Status")
)

app <- iSEE(sce, initial=initial)
shiny::runApp(app, launch.browser = TRUE)
```

**Comment by kevinrue** [comment]
Do you feel like giving it another go? I've even added some sanity checking code that makes sure invalid colData/rowData names are discarded (with a warning) rather than crash the app.

I think I'm pretty much ready to merge and release a new version. But being close to the next release, I'd rather be careful not injecting a bug that would need urgent fixing.

**Comment by kevinrue** [comment]
I've just pushed version `2.9.11` to Bioconductor. It should be available in a couple of days. In the meantime you should be able to install from GitHub for testing:

```r
devtools::install_github("iSEE/iSEE")
```

**Comment by kevinrue** [comment]
Coming soon:
![image](https://user-images.githubusercontent.com/5769108/193835111-20de6721-6dca-4c6e-bc14-6be857d26aa0.png)
