### ISSUE TITLE
Hide interface Visual Parameters

### ISSUE THREAD

**Issue by daymecita** [iSEE/iSEE#611]
Hello!

I have added a new panel that creates a Dimensionality reduction plot for differential abundance analysis. It inherits from the standard ReducedDimensionPlot class. I am not interested in showing the three boxes Data Parameters, Visual Parameters and Selection Parameters. I could hide two of them but Visual Parameters is still shown. Do you know why? 
This is part of the code I use: 
AllClasses.R
`setClass("DAReducedDimensionPlot", contains="ReducedDimensionPlot", slots=c(Comparison="character"))`
panel_DAReducedDimensionPlot.R
`setMethod(".hideInterface", "DAReducedDimensionPlot", function(x, field) {
  if (field %in% c(.dataParamBoxOpen, .selectParamBoxOpen, .visualParamBoxOpen)) {
    TRUE
  } else {
    callNextMethod()
  }
})
`
This is how my panel looks: 
![image](https://user-images.githubusercontent.com/100194518/208106166-5c3a75fc-f3a5-48bf-8fe0-1e188ac3e2c5.png)

I am using the latest iSEE version: 2.11.1
Thanks a lot for all you do for the community :)
Dayme

**Comment by daymecita** [comment]
Hi!

Any comments on my previous issue? 

Best, 
Dayme

**Comment by LTLA** [comment]
@kevinrue I think this could be resolved by switching to a `.collapseBoxHidden` at 

https://github.com/iSEE/iSEE/blob/51c83789dc692473faffad4766a2ea5242f46af4/R/interface_visual.R#L70

**Comment by kevinrue** [comment]
Woops. Completely forgot about this issue over the Xmas break, sorry.
Today's my last day before two weeks full-on teaching, and I've got a pretty packed schedule.
I'll see what I can do, when I can, but @LTLA seems to have the solution, so it'd be nice if you could prepare the PR. I could still test it on my end.

**Comment by kevinrue** [comment]
work in progress at #614

**Comment by kevinrue** [comment]
Looks like the fix is working. I need to do some minor cleanup and I'll merge. If you're in a rush, install and test the fix using
```r
remotes::install_github("iSEE/iSEE@kra-issue-611")
```

**Comment by kevinrue** [comment]
Fix released in iSEE 2.11.2.
