### ISSUE TITLE
Bug introduced by fixing issue 611

### ISSUE THREAD

**Issue by daymecita** [iSEE/iSEE#618]
Hello!

Thank you for fixing the issue described here: https://github.com/iSEE/iSEE/issues/611.
However it seems that something wrong was introduced since now the Visual Parameters tab looks like this for all panels:
![image](https://user-images.githubusercontent.com/100194518/216397597-ccffd711-955c-4247-a931-39d6c80f011b.png)

**Comment by kevinrue** [comment]
Thanks for reporting. Definitely didn't see that when I tested it during the fix. I'll test again ASAP.

**Comment by kevinrue** [comment]
Thanks for reminding me. Life was extremely busy the last couple of weeks.

**Comment by kevinrue** [comment]
Bugfix incoming at #620
