### ISSUE TITLE
Wrong annotation colors in Complex Heatmap

### ISSUE THREAD

**Issue by daymecita** [iSEE/iSEE#621]
Hello! 

I have recently noticed that the annotation colors on the heatmap are incorrect. The cell types on the bar don't match with the legend colors. See image below:
![image](https://user-images.githubusercontent.com/100194518/218105627-7ef58983-474c-4848-b291-88e37e54d0da.png)

However, when I download the plot the colors are correct. See image:
![image](https://user-images.githubusercontent.com/100194518/218107475-5d404911-4e7e-4819-adaf-e7b76dd491cf.png)

Could you please look into this when possible? Thanks a lot!
Dayme

**Comment by kevinrue** [comment]
Interesting. Thanks for reporting.

**Comment by kevinrue** [comment]
Hi.

I just tested now, using the devel version of iSEE (2.11.4) and a dummy dataset that simulates your situation (9 factor levels) and I cannot see any issue.

## Code

```r
library(iSEE)

ncells <- 100
nfeatures <- 10

set.seed(1)
se <- SummarizedExperiment(
    assays = list(
        counts = matrix(rbinom(ncells * nfeatures, 100, 0.1), nfeatures, ncells)
    ),
    colData = DataFrame(
        celltype = sample(head(LETTERS, 9), ncells, replace = TRUE)
    )
)
se

iSEE(
    se,
    initial = list(
         ComplexHeatmapPlot(
             PanelWidth = 12L,
             VisualBoxOpen = TRUE,
             ColumnData = "celltype"
         )
     )
)
```

## Live app

![image](https://user-images.githubusercontent.com/5769108/221145443-f4813a41-b958-4c05-bd5a-3f102f4a880a.png)

## Exported figure

![image](https://user-images.githubusercontent.com/5769108/221146254-487723f6-5182-4832-8f6b-7e0c52775c89.png)

## Conclusion

* Can you try using the devel version of iSEE?
* Can you give me the code of a reproducible example that has the issue for you? Your initial post only provides screenshots without sufficient details to reproduce your issue nor pinpoint its cause.
