### ISSUE TITLE
Add an option to order cells by feature value in reduced dimension plots

### ISSUE THREAD

**Issue by ccasar** [iSEE/iSEE#627]
Hi,
I had a quick look at the iSEE documentation but could not find a solution to this visualization problem.

**Is your feature request related to a problem? Please describe.**
Cells with higher feature expression may be hidden by other cells with lower expression due to the order of the cells. 

See these two UMAPs for example, where the same gene is shown but in the first plot the cells are sorted by gene expression while in the second plot, taken from iSEE, the cells are sorted by their default order:

![scanpy_gnly](https://user-images.githubusercontent.com/2711108/228249318-52dca577-5d50-478f-9df6-3480f049068e.png)

![isee_gnly](https://user-images.githubusercontent.com/2711108/228249343-41001888-365a-42d1-a95b-534988ec64b0.png)

In the second plot you would probably miss the GNLY expressing cells within the red rectangle.

**Describe the solution you'd like**
Add an option to sort cells by feature value in the reduced dimension plot, i.e. similiar to Seurat's `FeaturePlot(x, order = TRUE)` option.

**Comment by federicomarini** [comment]
I am not sure the thing you see done in scanpy is the behaviour you would expect/hope to see.
The fact of seeing this "enrichment" of cells might be an artifact of how the graphics system colors "things".

See this small reprex I actually put together recently, for another purpose.

```
set.seed(42)
fake_data <- data.frame(
  x = rnorm(n = 100000, mean = 0, sd = 1),
  y = rnorm(n = 100000, mean = 0, sd = 1)
)
fake_data$group <- c(rep("g1", 50000),
                     rep("g2", 50000))

fake_data$group_rand <- sample(c("r1", "r2"), 100000, replace = TRUE)

table(fake_data$group)
table(fake_data$group_rand)
# see the comparable amount of points

plot(fake_data$x, fake_data$y, col = as.factor(fake_data$group))

plot(fake_data$x, fake_data$y, col = as.factor(fake_data$group_rand))

# same with ggplot
library("ggplot2")

ggplot(fake_data, aes(x = x, y = y, col = group)) + geom_point() + theme_bw()
ggplot(fake_data, aes(x = x, y = y, col = group_rand)) + geom_point() + theme_bw()

```

Output:

![image](https://user-images.githubusercontent.com/7447478/228272492-9a1c9556-302a-4574-bc99-da9668af5c7b.png)

![image](https://user-images.githubusercontent.com/7447478/228272557-df89f0b6-cf91-410d-9c65-abcee0a78bd8.png)

![image](https://user-images.githubusercontent.com/7447478/228272636-7b328fd4-3361-4c03-afdf-d8d8f9391b85.png)

![image](https://user-images.githubusercontent.com/7447478/228272702-f6a0abde-543c-4533-ad76-d7707daf33fd.png)

This is to say: maybe there is some kind of silver lining in having it "hidden" if the pattern is not that major/evident.
I'll let the others weigh in with their opinion on this :wink#

**Comment by federicomarini** [comment]
Apart from the timeline of features we could and should implement: I would say that the way you observe it in the scanpy plot is arguably... if not wrong, at least very very misleading.
You would "try to see" a clump of cells, whereas... well, there is not such a "real clump". 
Just my two cents 😉

**Comment by ccasar** [comment]
Thanks for the discussion!

> Believe it or not, we have long considered this problem of overplotting in **iSEE**. The current solution is to scramble the points so that the input order does not dictate the final visualization (e.g., if cells from different batches were grouped together, our scrambling ensures that the last batch does not drive the entire visualization). This approach is probably the most appropriate if you want the observed color mixture to accurately reflect the underlying distribution of values.

I was not aware that iSEE is already shuffling cells in this way. So a suitable solution is already in place and I'll close this issue.

**Comment by kevinrue** [comment]
Just as a pointer:

> I was not aware that iSEE is already shuffling cells in this way. 

Make sure to have a look at the R script dynamically reported in the iSEE app. This is the _exact_ code that is run to produce each of the panel outputs.

![image](https://user-images.githubusercontent.com/5769108/228551651-355e80f3-e300-48d7-a0e8-3674b1610f43.png)

You will see the call to `sample()` which randomises the order of points on the fly.

![image](https://user-images.githubusercontent.com/5769108/228552620-f99d7c3c-034b-4547-8a1f-487312723dfc.png)
