### ISSUE TITLE
.addSpecificTour cannot be used to edit panel specific UI tours. Global tour cache is cleared upon iSEE() function call.

### ISSUE THREAD

**Issue by lee-t** [iSEE/iSEE#628]
I might reveal a severe lack of knowledge about R development but here's my issue. I've been trying to modify the rintrojs tour of a ColumnDataPlot in my app. I want to modify the tours specific to individual UI elements for each Panel in my app that is launched in a script with `iSEE::iSEE(sce)`. 
I have been trying to modify using the UI-specific tour functions `.addSpecificTour("ColumnDotPlot","ColumnDataPlotNA", cdattour(), force=TRUE)`. It seems that upon launching the iSEE app, the .global_tour_env() var is automatically cleared and the UI element reverts to defaulttours as defined in the methods.  I must be using this UI function incorrectly or is there no way to modify the panel tours without changing the underlying .definetours() for that panel class?

**Comment by kevinrue** [comment]
Sorry, I stumble on this issue while quickly going through the full list. Seems like I failed to reply when you first opened the issue.

I've been working on packages downstream of iSEE for the last few months, and will come back to iSEE itself properly during the next release cycle.

That being said, I think you're not using the function correctly.  The second argument should be the name of the field (i.e., class slot) that is associated with the UI element. I would point you to the iSEE codebase, to see how the function is used, but I'm sure you've done that already, and admittedly our codebase has become quite complex and hard to read.

You may find the simpler codebase of my more recent package iSEEde easier to read, e.g.
https://github.com/iSEE/iSEEde/blob/devel/R/DETable-class.R#L145
