### ISSUE TITLE
"stop app" button?

### ISSUE THREAD

**Issue by vjcitn** [iSEE/iSEE#630]
**Is your feature request related to a problem? Please describe.**
Is there a controlled way to exit iSEE or do we use interrupt to get out?

**Describe the solution you'd like**
actionButton with stopApp can be used

**Describe alternatives you've considered**
control-C

**Additional context**
I looked through doc for "stop" or "exit iSEE" with no hits ... but may have missed something.

**Comment by kevinrue** [comment]
Good feature request!

You haven't missed anything. It's not implemented yet. 

I must say that I haven't seen many apps with a stop button. Seems like closing the app window is standard practice/expectation. Not the most elegant way, for sure!

I'll have a stab at it at the next opportunity. I seem to remember @LTLA looking at "end of app" behaviour at some point too. Might be a nice opportunity to combine and consolidate functionality.

**Comment by LTLA** [comment]
I vaguely remember that the `stopApp` was implemented to return the selections. But I think we removed that in favor of the tracked code.

In general, it didn't seem that useful to have a stop button, given that it wouldn't make much sense for deployed apps (what else would the server do, if not show the app?), and CLI users could just Ctrl-C. I guess you could add some fancy hooks to instruct the server to, e.g., return to a homepage on app stop.

**Comment by federicomarini** [comment]
Note to guide the implementation of this (which can be no-matter-what relevant when running apps in containers and liberate the used resources):

* a fifth button up top right (icon: cogs?)
* with a subitem with the desired button (icon: stop? square?)

**Comment by federicomarini** [comment]
Working on this in https://github.com/iSEE/iSEE/tree/showstopper
