### ISSUE TITLE
Let user define colormap in the landing page

### ISSUE THREAD

**Issue by ppaxisa** [iSEE/iSEE#631]
**Is your feature request related to a problem? Please describe.**
End users (with no coding capability) would like to choose the colors before they start the app. I wrote some shiny elements to let the user make color choices within the landing page:
https://github.com/ImmuneAxisa/iSEE_app/blob/main/create_lp_wrapper.R
 Eg they choose the path to the object to load and can also have a menu with a set of colors (I predefined). 

Given user input in the landing page I create a new `colormap`. But as far as I know there is no clean way to pass the `colormap` created within the landing page to the actual iSEE app. My hack is to add that to the landing page code right before starting the app to change `colormap` within the `FUN` environment:
`assign("colormap", colormap, envir =  environment(FUN))`

**Describe the solution you'd like**
I guess the solution I would like is for `FUN` to have a `colormap` argument (which might have a default, so it does not create any problem is unspecified).

**Describe alternatives you've considered**
Maybe be there is an actual way of specifying this within the landing page but I could not find it. Apologies if I missed it.

**Comment by kevinrue** [comment]
Thanks for the feature request and the work you've already put in finding a workaround.

This is a great idea and I can foresee an implementation, which will likely be based on the app maintainer defining any number of colormap objects in scripts, which can then be displayed as a selectInput in the landing page.

The basic functionality described above should not be too complicated to implement, but as a user, I would probably like a preview of the colors before launching the app, which would take a bit of extra thinking to display nicely. I'm throwing the thought here as a reminder, but I would really keep that out of the initial implementation so that you get the basic functionality released faster.

I'm teaching full time this week, and I've got a few other things waiting for my attention in the coming weeks, but I'll try to have a look at this reasonably soon. Don't hesitate to revive this thread if you don't hear from me.

**Comment by ppaxisa** [comment]
Hi Kevin, 

To revive this: what I meant would be just to modify the `FUN` definition to include a `colormap` argument with the current default (I guess returned by `ExperimentColorMap`?). In this way the behaviour of the package would not change if using the default landing page  but people working on custom landing pages would have the liberty to customise the colormap and pass it to `FUN`. 

Ultimately this option could be described in the vignettes? I currently have my landing page plotting a ggplot to display the palettes but this is really skeletal so far. And not sure how to elegantly scale that up to a large set of palettes... But I don't think this needs to be maintained within iSEE as long as there is a basic explanation that the option exists and advanced users have the possibility to build their colormaps in the landing page.

**Comment by kevinrue** [comment]
Thanks for reviving this. You did well.

Had a baby in the meantime, but I'm partially available to work on this. 

Let's do the same thing. I'll do my best to get to it, but do ping me again if you don't hear from me in a couple of weeks. Hopefully I'll avoid that situation this time  ;)

**Comment by kevinrue** [comment]
I'm pushing a fix to github right now.

Before I lose it, here's the script that I used for testing:

```r
# Alternative approach, to create a landing page
# that opens one of the datasets from the scRNAseq package.
library(scRNAseq)
all.data <- ls("package:scRNAseq")
all.data <- all.data[grep("Data$", all.data)]

se_test <- scRNAseq::AztekinTailData()

colormaps <- list(
    viridis = ExperimentColorMap(global_continuous = viridisLite::viridis),
    magma = ExperimentColorMap(global_continuous = viridisLite::magma)
) 

.landing_page <- function() {
    function (FUN, input, output, session) {
        requireButton <- TRUE
        
        # nocov start
        output$allPanels <- renderUI({
            tagList(
                selectInput("colormap", "Colormap", choices = c("viridis", "magma"), multiple = FALSE),
                if (requireButton) actionButton(iSEE:::.initializeLaunch, label="Launch", style=iSEE:::.actionbutton_biocstyle)
            )
        })
        # nocov end
        
        target <- iSEE:::.initializeLaunch
        
        # nocov start
        observeEvent(input[[target]], {
            se2 <- se_test
            if (is(se2, "try-error")) {
                showNotification("invalid SummarizedExperiment supplied", type="error")
            } else {
                init <- NULL
                if (is(init, "try-error")) {
                    showNotification("invalid initial state supplied", type="warning")
                    init <- NULL
                }
                
                FUN(SE=se2, INITIAL=init, COLORMAP=colormaps[[input$colormap]])
            }
        }, ignoreNULL=TRUE, ignoreInit=TRUE)
        # nocov end
    }
}

app <- iSEE(landingPage=.landing_page())
if (interactive()) {
    shiny::runApp(app, port=1234)
}

```

**Comment by ppaxisa** [comment]
Hi Kevin,

first, congrats on the baby! and kudos to you for bothering with GitHub issues during those busy times ^^. And thanks for the praise on coding the shiny landing page, this is my first dive in shiny and it's been lots of fun!

One small question: I guess I need to install the devel version to try this out?

Thanks for the help!

**Comment by kevinrue** [comment]
Thanks!

Yes, either devel (best practice and more reliable), or you could try directly from GitHub (riskier, fewer compatibility checks)
