### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by KerryAM-R** [iSEE/iSEE#635]
**data cleaning to remove low expressing genes**
I saw from today that the Volcano plots displayed did not appear to be from the adjusted p-value results. I'm not sure if you are aware that  DESeq2 only removes the low expressing genes in the adjusted P-value column, and not before applying the model. I think this should be the default display and to remove non-expressing genes (Bulk RNA-seq).

**Comment by kevinrue** [comment]
Hi. You've opened this issue on `iSEE`. It seems that you refer to functionality implemented in `iSEEde` https://github.com/iSEE/iSEEde

Feel free to reopen the issue there.

That being said, I encourage to first read this thread (among others): https://support.bioconductor.org/p/98442/
I will summarise it with the last sentence in the thread:
> For these reasons, the p-value and not the adjusted p-value is the preferable quantity to use in a volcano plot.
