### ISSUE TITLE
Extend iSEE visual toolkit to TreeSummarizedExperiment-specific features

### ISSUE THREAD

**Issue by RiboRings** [iSEE/iSEE#636]
Hi!

iSEE provides a great interface to visualise the components of SummarizedExperiment as well as SingleCellExperiment instances. However, to the best of my knowledge iSEE does not yet target elements that are typical of TreeSummarizedExperiments, such as row- and colTrees (depicting phylogeny and sample hierarchy, respectively), and taxonomically agglomerated experiments (in the altExp slot).

With that said, I propose to expand the visualisation toolkit of iSEE with:
1. panels for row and colTree (if not empty), with options to adjust data, visual and selection parameters
2. if altExps are provided, give the option to visualise data at different taxonomic levels

As an alternative to the 2nd point, the user could also do `iSEE(altExp(tse, "exp_name"))`, but this way the command should be run for each and every altExp and such layers could not be visualised jointly in a single interface.

Looking forward to your thoughts :)

**Comment by kevinrue** [comment]
Hi

Thanks for the interest and the suggestion!

Indeed, iSEE hasn't been developed in that direction yet.

Both options sound sensible at first glance / on paper. 

I'm not a frequent user of `TreeSummarizedExperiment` even though I've been involved with it in the past, so I'm more than rusty when it comes to usage.

From experience (of other proposals for iSEE extensions), I would say that the best way to get started it to collect example bits of code that you regularly use to plot `TreeSummarizedExperiment` information, as this is the code that iSEE panels will need to emulate based on interactive user inputs.
In other words, have a look at the code reported in live iSEE apps. If you can write the code that you're expecting to see there, then we can "teach" iSEE to generate that code based on the selections made by users in the interface.

Additionally, a screenshot of the plots you'd like to see would also be useful for us to visualise what you're trying to achieve (on a particular dataset).

Bonus point if you can include the code to fetch and preprocess a publicly available `TreeSummarizedExperiment` object that we can use to reproduce your plots and while running prototype apps to test the new panels.

I won't hide that writing the actual "iSEE code" underlying each panel requires quite a bit of time and knowledge (we've written documentation to help contributors, but still), but if you can at least provide the above (code, data, screenshots), that would help us get started.

Feel free to paste code and screenshots in this thread to keep it all in one place for now. We can think of a better place if things get too busy here.

Thanks again!

**Comment by federicomarini** [comment]
To provide a bit more context to you, @kevinrue :
Giulio was also attending EuroBioc2023 these days, and we already had a couple of very nice discussions that confirm indeed how useful such a support for treeSE could be.

I think it can be an excellent starting point if we can point @RiboRings to some of the kickstarter-level documentation we had for writing a panel from the scratch.
Or as an alternative, have him rewind a bit the process via commit history and see what was added sequentially.

I suggested to keep the conversation going also on our biocslack channel, maybe there it becomes even more fluent/low barrier to make this happen 😉

**Comment by kevinrue** [comment]
Thanks for the context. I should have guessed!

Anyway, yes to continuing on Slack and revisiting our documentation for developers. I think it's a bit out of date now, but I've started a new book which aims at just that. Early days now, but I'll link in due time.

Have a good weekend all!

**Comment by RiboRings** [comment]
Thanks for all the useful remarks! As @federicomarini pointed out, I will give it a go with the help of your documentation and keep you up-to-date on the progress.

Good weekend to you as well!

**Comment by kevinrue** [comment]
> @kevinrue  Anyway, yes to continuing on Slack and revisiting our documentation for developers. I think it's a bit out of date now, but I've started a new book which aims at just that. Early days now, but I'll link in due time.

Actually, I've started sharing the draft few chapters of the book elsewhere, so why not here:  https://isee.github.io/iSEETheBook/

It's far from the anticipated chapters about writing iSEE extension (I want to cover the end-user facing basics first) but I'm happy to receive feedback. (I'll add a section in the book pointing to the GitHub repository so that readers can more easily open issues and send feedback)

> @RiboRings I will give it a go with the help of your documentation

Actually, could you do me a favour and list links to pieces of documentation that you have been using?
I've started listing resources here: https://isee.github.io/resources.html 
I'm curious which ones you are using and whether there are any that you are using which are missing from the page.
Feel free to open an issue here for any documentation I haven't listed yet: https://github.com/iSEE/iSEE.github.io/issues

I can't give an ETA but I'm keen to take iSEEtree for a test drive!

**Comment by RiboRings** [comment]
> Actually, could you do me a favour and list links to pieces of documentation that you have been using?

Initially I tried to follow the "worked examples" here: https://isee.github.io/iSEE-book/. However, it was quite tricky to transfer those ideas to my own custom panel, because I didn't really know which case study was the most appropriate to follow (e.g., inherit from RowDataPlot because mine is a row-wise plot, or inherit from Panel because the plot layout is a tree?). Then I came across the vignettes "createCustomPanels", used the createCustomPlot as a skeleton for my new panel and worked backwards.

> but I'm happy to receive feedback

I think it would be really helpful if the documentation could explain how to create a panel that is a Minimum Viable Product, and then show how to expand its features in different directions.

**Comment by kevinrue** [comment]
(Not forgetting about you.. Just really swamped for the next few weeks.. Actually, iSEE-related!)

**Comment by RiboRings** [comment]
Hi! From my side this issue can be closed since now we have [iSEEtree](https://github.com/microbiome/iSEEtree).

**Comment by kevinrue** [comment]
Thanks for your contribution and for reminding us to close this issue.
