### ISSUE TITLE
Incorporating information from rowRanges

### ISSUE THREAD

**Issue by csoneson** [iSEE/iSEE#637]
At the moment, `iSEE` is not making use of any information present in the `rowRanges`. Any thoughts about adding this data as columns in the `rowData`, e.g. in https://github.com/iSEE/iSEE/blob/devel/R/cleanDataset.R? Perhaps with a prefix that indicates where they came from (and to avoid overwriting existing columns).

**Comment by federicomarini** [comment]
This is basically the written follow up to what we discussed briefly at EuroBioc2023, am I right?

I have nothing against a coerced auto-conversion, maybe with a message popping up in the console and/or to the UI (showNotification?) to let the user know something has happened on that.

About the prefix: `rr_NAME_OF_THE_ITEM` seems safe enough to me.

**Comment by kevinrue** [comment]
Going through the issues. I've got no good suggestion at this time.

Whatever the prefix used, I'm concerned about what's displayed to users in-app. 

Maybe a concrete example would make it easier to discuss practicalities.

**Comment by kevinrue** [comment]
`rowRanges_NAME_OF_THE_ITEM`

Optionally, display notification in-app
