### ISSUE TITLE
Running app from remote server (cluster/cloud)

### ISSUE THREAD

**Issue by davismcc** [iSEE/iSEE#64]
Will this run from a remote cluster? 

Two use cases: 
(1) I have a very large dataset and can't/don't want to analyse it on my local laptop/desktop. Will I be able to access the shiny app locally through ssh port forwarding or similar? (the rmote pkg by Ryan Hafen is a good example/motivation there) 
(2) I produce a dataset for my biological collaborator on my institute's cluster. The dataset is too        big to transfer/they don't have the setup to run iSEE locally on this big dataset. Can I make the app available for them to access through a browser?

Could we do the above but from a cloud environment (AWS/GCP etc)? This  would be great for exploring HCA data which will end up on all of those platforms.

**Comment by kevinrue** [comment]
I'm up-voting and keen to help to see this working, at least point (2).

Just to clarify point (1): in iSEE, analysis is limited to visualisation. All computationally intensive steps should be performed before opening the app, and stored in the appropriate slot of the SCE object. At least unless we find a _really_ efficient way to process data on clusters or cloud-based systems. Low priority at the moment, I think.

(2) Indeed, I have already installed the development version of the app on a collaborator's laptop, and had to send them an RDS file with the preprocessed object. Far from ideal.
I'm keen to discuss this as soon as we have the main functionalities of the app in place and stable.

**Comment by kevinrue** [comment]
To answer @davismcc 's point (1):
We have an _RStudio_ server over here, and I've been successfully running the app as a second tab in my browser. More clearly:
* RStudio is open in a tab of my web browser.
* I can successfully run the app with the example code in `?iSEE`, but also for other local data sets.
Note that in this case, the app is running on the cluster, and only displayed to the client (apart from notable `DT::datatable` exceptions)

(2) would be better addressed by a _Shiny_ server.

**Comment by slowkow** [comment]
@davismcc 

# Access a remote app from your laptop

Steps:

1. Launch the Shiny app on your server.
2. Open an ssh tunnel from your laptop to the server.
3. Browse the app on your laptop in your web browser.

On your server

```r
# make the app object somehow...
shiny::runApp(app)
```
```
Loading required package: shiny
Listening on http://127.0.0.1:4694
```

On your laptop

```bash
ssh -N -L 4694:localhost:4694 username@servername.org
```

Open your web browser and navigate to: http://localhost:4694

**Comment by slowkow** [comment]
# Expose a remote app to the public

Steps:

1. Setup a public web server that runs nginx or Apache. You can use Amazon EC2, Linode, DigitalOcean, etc.
1. Launch the Shiny app on your lab server.
2. Open an ssh tunnel from your public web server to the lab server.
3. Serve the app to the public on your webserver.
4. (Optional) Set up basic HTTP auth for username/password access to your app.

## On your lab server

```r
# make the app object somehow...
shiny::runApp(app)
```
```
Loading required package: shiny
Listening on http://127.0.0.1:4694
```

## On your web server

Install Apache.

Open a tunnel to your lab server:

```bash
ssh -N -L 4694:localhost:4694 username@servername.org
```

Setup your Apache website configuration file:

```xml
# /etc/apache2/sites-available/example.com.conf
<VirtualHost *:80>
  ServerName example.com
  Redirect /app /app/
  ProxyPass /app/ http://localhost:4694/
  ProxyPassReverse /app/ http://localhost:4694/
  ProxyPreserveHost On
  # Optional: Only allow authenticated users to view the app.
  <Location /app/>
      AuthType Basic
      AuthName "Restricted Access - Please Authenticate"
      AuthUserFile /etc/httpd/htpasswd.users
      Require user myusername 
      # To add a new user: sudo htpasswd /etc/httpd/htpasswd.users newuser 
  </Location>
</VirtualHost>
```

Restart Apache:

```bash
sudo service apache2 restart
```

## On your laptop

Open your web browser and navigate to: http://example.com/app/

Login with the username and password that you setup with `htpasswd`.
