### ISSUE TITLE
Order points based on expression

### ISSUE THREAD

**Issue by daymecita** [iSEE/iSEE#643]
Hello iSEE team, 

Could you implemment a feature that allows to plot cells with higher expression of a specific gene first on the Reduced Dimension plot when coloring by feature name? 

Thanks a lo for keeping improving the app :)

Dayme

**Comment by LTLA** [comment]
Might be worth reading #627.

**Comment by kevinrue** [comment]
@daymecita 

Thanks for your feedback.

Without repeating the discussion linked by @LTLA  , are you satisfied that your feature request is not the best idea?

I'll close the issue for now. Feel free to come back and describe a use case where this feature would be worth implementing.
