### ISSUE TITLE
Checking for co-expression of 2 genes

### ISSUE THREAD

**Issue by lcolladotor** [iSEE/iSEE#649]
**Is your feature request related to a problem? Please describe.**

A question I got after https://youtu.be/i5I_mFOsGks from a LIBD colleague was: how can I check for co-expression of 2 genes?

**Describe the solution you'd like**

* Maybe one of those dotplots where you have the clusters on both X and Y, but then have the size of the dot related to expression of a gene (or both), and the color of the dot related to the correlation. Something like that?
* Maybe something like https://twitter.com/BiotechPedro/status/1777033785256583196
* Maybe some other 2 gene-based visualization: I recognize this is a fairly open-ended question.

**Describe alternatives you've considered**

* I showed how you can use the _Feature Assay plot_ to plot expression of gene 1 vs gene 2, though that scatterplot shows many points.
* The person asking the question wasn't interested in a heatmap.

**Additional context**

* The person who asked me the question mentioned that BioTuring had some features for this. I don't know exactly what they are though.

**Comment by kevinrue** [comment]
Thanks for the feedback and opening this issue as a sticky note to look into when we get the chance!

Obviously the clearer the request, the faster it can be implemented, but opening the issue is the first step to refine the desired functionality and plan its implementation :)

**Comment by federicomarini** [comment]
I am always a bit extra careful with this form of blending for the 2-gene based viz.
Alone the order of how these individual points are plotted can (or cannot) mislead one in thinking/seeing a cluster or a conglomerate of cells.

Faceted representations are IMHO very good, but of course they still don't solve the "all-in-one figure" issue.
Maybe worth some thoughts of having such a custom panel "fully" implemented?

**Comment by lcolladotor** [comment]
Hi,

I've relayed back your feedback to my LIBD colleague and asked if they have screenshots of the actual visualizations they would like to see for co-expression of 2 genes.

I agree with you that narrowing down the scope will be useful.

Best,
Leo

**Comment by lcolladotor** [comment]
Hi again,

Here's the specific anonymized example that my LIBD colleagues relayed to share here.

<img width="1080" alt="pastedImage" src="https://github.com/iSEE/iSEE/assets/2288213/2cb3933c-f9c3-450e-ad4c-2db18f1e0aed">

**Comment by kevinrue** [comment]
Two options:

* Implement a custom panel class
* Add correlation data in `rowData()`; use existing `RowDataPlot()` to add two panels to the UI, one for the P-value on the Y axis, one for the correlation on Y-axis. Then facet by region. To label genes, filter them in a table or select them in another panel, transmit the selection, and color by incoming row selection.
