### ISSUE TITLE
Selection options documentation + filtering based on specific gene expression

### ISSUE THREAD

**Issue by lcolladotor** [iSEE/iSEE#650]
**Is your feature request related to a problem? Please describe.**

Related to #649, that same LIBD colleague was asking about ways to subset the data interactively. 

**Describe the solution you'd like**

What are the different selection options? Can you select cells based on a gene having expression greater than some threshold? What about 2 genes? (say the co-expressed ones from #649).

**Describe alternatives you've considered**

* I did show how you can make a selection on the reduced dimensions plot panel and how this reflects on the feature assay plot (with alpha-blended points for those that are not selected).

**Additional context**

There was some interest on being able to make some other computations on the fly. I did mention that `iSEE` can be expanded with custom panels, although I personally have no experience making them. I also said that it could be good to make an R package for those custom panels if you want to share them with others.

**Comment by csoneson** [comment]
> What are the different selection options? Can you select cells based on a gene having expression greater than some threshold? What about 2 genes?

You could approach this using Feature Assay Plots, selecting points (cells) with expression above a certain threshold - you can also chain multiple such plots together to select only cells that express both genes highly (transmit first selection to second panel, subset to selected points, make another selection, etc).

**Comment by lcolladotor** [comment]
Thanks for the info @csoneson!

I had a few spare minutes, so I recorded myself playing around with http://shiny.imbei.uni-mainz.de:3838/iSEE/# and trying to follow the suggestions you mentioned. I was able to use 2 `Feature assay plot` panels and chain them together, but I'm not sure if you were suggesting a solution involving just 1 `Feature assay plot` panel (which I didn't figure out how to implement).

Here's the video (it'll be available for 6 months). Zoom is processing the video right now, but it should be available in less than 10 min.

https://jh.zoom.us/rec/share/xfDrO54wSRAiywT_kSIXpXU9brvd8SFaL6e2wUvLHb6MTk01VxVwBe_dYEbkIl7Z.smQ2HxaPaj527hws 
Passcode: C$=03ApG

**Comment by csoneson** [comment]
Nice :) Yes, indeed, I was referring to using two (or more) linked `Feature assay plot` panels. It's similar in spirit to the gating workflow for cytometry data, which is illustrated e.g. in one of the initial example apps (https://marionilab.cruk.cam.ac.uk/iSEE_cytof/) - notice how `Feature assay plot` 4, 5 and 6 are linked together. 

Here's another minimal example, with the Allen data: 
```
library(scRNAseq)
library(scater)
library(iSEE)
sce <- ReprocessedAllenData(assays="tophat_counts")
sce <- logNormCounts(sce, exprs_values="tophat_counts")
sce <- runPCA(sce, ncomponents=4)
initial <- list(FeatureAssayPlot(Assay = "logcounts", YAxisFeatureName = "Serpine2"),
                FeatureAssayPlot(Assay = "logcounts", YAxisFeatureName = "Bcl6",
                                 ColumnSelectionSource = "FeatureAssayPlot1",
                                 ColumnSelectionRestrict = TRUE),
                ReducedDimensionPlot(Type = "PCA", ColorBy = "Column selection",
                                     ColumnSelectionSource = "FeatureAssayPlot2"))
iSEE(sce, initial = initial)
```
Making a selection in the first `Feature assay plot` panel restricts the set of points shown in the second, where now an additional selection can be made - the final selected points are highlighted in the PCA.

**Comment by csoneson** [comment]
The approach above works for any number of genes. If you only want to select based on two genes, you can get away with one `Feature assay plot` (with one gene on the x-axis and the other on the y-axis): 

```
initial <- list(FeatureAssayPlot(Assay = "logcounts", XAxis = "Feature name",
                                 XAxisFeatureName = "Serpine2", 
                                 YAxisFeatureName = "Bcl6"),
                ReducedDimensionPlot(Type = "PCA", ColorBy = "Column selection",
                                     ColumnSelectionSource = "FeatureAssayPlot1"))
iSEE(sce, initial = initial)
```

**Comment by lcolladotor** [comment]
That's awesome!!! Thanks for the minimal examples @csoneson! I'll likely make a short video about this and share it, as I don't think that any of us at LIBD were aware about how to do this.

Thanks again!
