### ISSUE TITLE
[BUG] http://shiny.imbei.uni-mainz.de:3838/iSEE/ doesn't let you use the quick tour functionality

### ISSUE THREAD

**Issue by lcolladotor** [iSEE/iSEE#651]
**Describe the bug**

Related to #649.

A few documentation links point to http://shiny.imbei.uni-mainz.de:3838/iSEE/ as an demo for the Allen dataset. The quick tour is also supposedly only enabled for this dataset (though it has be from using `?iSEE`). However, the quick tour doesn't work at http://shiny.imbei.uni-mainz.de:3838/iSEE/.

<img width="244" alt="Screenshot 2024-04-16 at 10 44 40 AM" src="https://github.com/iSEE/iSEE/assets/2288213/55e50442-1f50-4060-beb6-dc0eb7b2b943">

Maybe the Allen dataset example compatible with the quick tour has been deployed elsewhere. If so, then it'd be good to update the doc links to point to the right URL.

**To Reproduce**

Open http://shiny.imbei.uni-mainz.de:3838/iSEE/.

**Expected behavior**

I expected that the quick tour would work there. I wanted to 

**Screenshots**

See above

**Desktop (please complete the following information):**
 - OS: macOS 14.3.1 
 - Browser: Google Chrome
 - Version: 123.0.6312.122 

**Additional context**

This was part of a demo for users who are not R coders. Aka, we can't use R and run `?iSEE` .

**Session info (please complete the following information)**

Not relevant, only using browsers since this was a demo for users.

**Comment by federicomarini** [comment]
I think I know the problem, it can be that I am using a "snapshotted" version of the allen dataset and that does not pass the heuristics we define here: https://github.com/iSEE/iSEE/blob/devel/R/defaultTour.R

Let me have a look at that again ;)

**Comment by federicomarini** [comment]
Should be fixed now @lcolladotor 

<img width="988" alt="image" src="https://github.com/iSEE/iSEE/assets/7447478/d67630c4-e97e-47f8-821c-684704e86c42">

Just ping me if we can close this 😉

**Comment by lcolladotor** [comment]
Awesome! It does work. Thanks for the quick fix!

**Comment by federicomarini** [comment]
Sorry I did not catch that earlier, and thanks to you for the thorough use&testing!
F

**Comment by lcolladotor** [comment]
No worries! I'll surely teach about `iSEE` at https://meetings.cshl.edu/courses.aspx?course=C-DATA&year=24, so the update will come in handy then ^^.

**Comment by federicomarini** [comment]
Oh fantastic, feel free to grab any material from the existing workshops and adapt them to your needs!

I will also be delivering a full-day, in-depth workshop on iSEE in a couple of weeks, let me know if you need more inspiration from the experience there!

**Comment by lcolladotor** [comment]
These ones https://isee.github.io/resources.html#workshops? Sure, I'll take a peak at them.

My previous materials are at https://lcolladotor.github.io/cshl_rstats_genome_scale_2023/isee-introduction.html which comes from the Spanish course I teach for LCG-UNAM at https://lcolladotor.github.io/rnaseq_LCG-UNAM_2024/objetos-de-bioconductor-para-datos-de-expresi%C3%B3n.html#isee (and earlier versions).

Anyway, I'm thinking of teaching more about `iSEE` from a user perspective in the future, with just the basics from a coder perspective.


Good luck with full-day upcoming workshop!
