### ISSUE TITLE
export .selectInputHidden

### ISSUE THREAD

**Issue by RiboRings** [iSEE/iSEE#653]
Hi!

Would it be possible to export .selectInputHidden? This way I wouldn't need to import it with ::: in iSEEtree. I can also make a PR if you like.

Thanks!

**Comment by kevinrue** [comment]
It’s on the roadmap, specifically to export all constants and slot names. I just want to do it in a systematic and sustainable way as there are dozens of them.Maybe for this one, I’ll export once more the value on its own though. PR welcome if you have more time than me (won’t work this weekend)Thanks!On 25 May 2024, at 12:55, Giulio Benedetti ***@***.***> wrote:﻿
Hi!
Would it be possible to export .selectInputHidden? This way I wouldn't need to import it with ::: in iSEEtree. I can also make a PR if you like.
Thanks!

**Comment by kevinrue** [comment]
Closed by #656
