### ISSUE TITLE
Row/column data tables should ignore ordering of multiple selections

### ISSUE THREAD

**Issue by LTLA** [iSEE/iSEE#657]
Currently, when `Row/ColumnDataTable` instances accept a multiple selection, they are subject to the ordering of rows/columns in the selection, e.g., 

https://github.com/iSEE/iSEE/blob/8f32b92fb8343bc77a16988cc3afc70d65b961fb/R/panel_ColumnDataTable.R#L140

We can see that `tab` is now ordered arbitrarily depending on what the upstream panel decided to pass along. I would wager that doing so is rather inappropriate, as the multiple selection doesn't have any concept of ordering. How the rows are ordered is the responsibility of the table, not of the upstream panels. A practical example for how this causes problems: the `RowDataTable` contains DE statistics and is already ordered meaningfully by p-value but receives a selection that changes that ordering.

So, a simple fix would be to switch to the same selection code used by the plots:

https://github.com/iSEE/iSEE/blob/8f32b92fb8343bc77a16988cc3afc70d65b961fb/R/family_ColumnDotPlot.R#L549

which gets rid of the ordering.

**Comment by kevinrue** [comment]
Makes sense.
