### ISSUE TITLE
Support for links in the appTitle box

### ISSUE THREAD

**Issue by RiboRings** [iSEE/iSEE#681]
Hi!

I would like to add a link to the title box of my iSEE-based app, so that when you click on it, it would bring you back to the home page (an https address). My app home page can be found at this link: https://miadash-microbiome.2.rahtiapp.fi/

When I try to use tags$a or HTML methods in the appTitle argument of iSEE(), the title is not rendered correctly and the link does not work.

Would it be possible to add this feature to the dashboard box in the main iSEE package?

Thank you in advance!

**Comment by federicomarini** [comment]
Hmm, scratch that, as this one works @RiboRings 

```
library(shinydashboard)
library(shiny)

ui <- dashboardPage(dashboardHeader(title = 
                                      tags$a(
                                        "Link to your home",
                                        target = "_blank",
                                        href = "https://miadash-microbiome.2.rahtiapp.fi/"
                                      )),
                    dashboardSidebar(),
                    dashboardBody("all the rest of the content"))

server <- function(input, output, session) {}

shinyApp(ui, server)


```

<img width="336" alt="image" src="https://github.com/user-attachments/assets/a3cab5c8-4663-40f5-aacd-69a605c3f1cf">

... but the same does not within iSEE

**Comment by federicomarini** [comment]
In theory, this 

```
iSEE::iSEE(appTitle = tags$a(
    "Link to your home",
    target = "_blank",
    href = "https://miadash-microbiome.2.rahtiapp.fi/"
))
```

would give the same behavior, but becomes rendered as...

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/adcd5da3-2459-4ee4-897a-db86d19d9253">

**Comment by RiboRings** [comment]
Hi!

Yes, that's exactly the strange behaviour I noticed when trying a tag$a or HTML() as appTitle arg of iSEE().

Thanks for the working example! Since I am making use of the other dashboard elements from iSEE, I was trying to get it to work, but I'll see if I find a workaround.

Thanks!

**Comment by federicomarini** [comment]
If you please keep us posted.

I actually cannot tell why this is not interpreted correctly, as all we do to the appTitle parameter is fairly minimal:

https://github.com/iSEE/iSEE/blob/99b262981644c983515ca50c3252fc3f7057b6ef/R/iSEE-main.R#L161-L163

**Comment by RiboRings** [comment]
Could possibly be that the ifelse function is picking only the first element in the tags array?

**Comment by RiboRings** [comment]
It works using an if else statement instead of the ifelse function!

```
    .set_title <- function(title) {
      if( is.null(title) ) {
        paste0("iSEE - interactive SummarizedExperiment Explorer v", packageVersion("iSEE"))
      } else {
        title
      }
    }
    
    iSEE_ui <- dashboardPage(
        dashboardHeader(
            title = .set_title(appTitle),
```

**Comment by federicomarini** [comment]
i.e. `ifelse` does something unexpected 

<img width="686" alt="image" src="https://github.com/user-attachments/assets/18f3c8f4-b287-4428-98a6-4fee22136299">

Well spotted!

**Comment by federicomarini** [comment]
As a bonus track content for you, ICYMI...

```
iSEE::iSEE(appTitle = "Your title 🦠")
```

<img width="473" alt="image" src="https://github.com/user-attachments/assets/d4085aa7-bb27-4a3e-bb98-bbffa6578cd0">

--> You can go wild with emojis as well in there 😉

**Comment by RiboRings** [comment]
Haha looks very appropriate!

Is it ok if I open a PR to fix this behaviour?

**Comment by federicomarini** [comment]
On it already as you type 😉 

... and taking a chance to update also the GHA

**Comment by RiboRings** [comment]
Great thank you so much!

**Comment by RiboRings** [comment]
> ... and taking a chance to update also the GHA

Have you considered rworkflows? No need to change GHA after new Bioc release.

**Comment by federicomarini** [comment]
So far it is almost as easy as changing `20` to `21`, since the rest should keep on working, but thanks for the heads up, I was not aware of that!
Will give it a good look

**Comment by federicomarini** [comment]
Solution coming in #682

**Comment by federicomarini** [comment]
I just merged that yesterday in 😉 
Give it the time it takes to build on the Bioc machines, or just grab the devel version from Github, now it is in `devel`

**Comment by kevinrue** [comment]
I've pushed upstream. Like Fede wrote, give it a couple of days. Feel free the re-open the issue if needed.

**Comment by RiboRings** [comment]
Fantastic, thank you!

**Comment by lcolladotor** [comment]
Since I saw that you mentioned `biocthis` and `rworkflows` in this thread, as an FYI you might be interested in https://lcolladotor.github.io/biocthis/news/index.html#biocthis-1174.
