### ISSUE TITLE
Panel for images related to single-cell experiment colData.

### ISSUE THREAD

**Issue by edemmott** [iSEE/iSEE#683]
I have colData in my single-cell experiment that links each cell to one or more .png images showing the cell of interest (more than one if multi-colour images were taken). as well as background images. I'd like to be able to display these in a panel so a user can highlight the cell of interest (e.g. in a reduced dimension plot, or column data table) and have this show in this new panel.

**Describe the solution you'd like**
New panel for image visualisation, relating to summerised/single-cell experiment column metadata. May require passing a second object e.g. a list of image files, alongside the sce.

**Describe alternatives you've considered**
I am steadily working through the custom panel vignettes and attempting to do this myself, but with my level of R this is going to take a while, and I'm struggling a bit with the examples!

**Comment by kevinrue** [comment]
Sounds like a fun feature!

Note that development of new functionality has hit a bottleneck due to lack of funding and spare time.

Will keep you posted if and when progress is made in this direction.

FWIW we had a recent success story whereby someone who is not a core developer of iSEE wrote their own package extension [iSEEtree](https://github.com/microbiome/iSEEtree) if you're feeling adventurous enough to try yourself :)

**Comment by edemmott** [comment]
Completely understand - I'll keep plugging away and post an update if I get it working!

**Comment by federicomarini** [comment]
Hey Ed, glad you made some progress so far.

I think I can speak in name of the whole team here by saying that probably the most efficient and "powerful" way to proceed would be via the definition of a fully fledged new panel type.

Maybe you can find the recent package demo we have presented at EuroBioc2024 useful?

https://isee.github.io/iSEEDemoEuroBioC2024/articles/workshop_isee_extension.html

**Comment by edemmott** [comment]
Thanks, yes thats helpful! Am cracking on with a new panel as you suggest.

**Comment by edemmott** [comment]
Just to update, have it working as a new panel type now. Still some tweaks and tidying up to do but it is working

**Comment by federicomarini** [comment]
Fantastic @edemmott - might be rather something for https://github.com/iSEE/iSEEu/ or a standalone package itself?

We do welcome contributions - and I am myself very excited to see how it looks like, if you dare to share 😉

**Comment by edemmott** [comment]
Its taken a little while... The preprint will follow in a week or so, but just made the repository public - included as part of an R package for single-cell multiplet detection/cell phenotyping. 

 cellenONEplot panel included. Will have an example on shinyapps.io as soon as it starts supporting R4.5.1... https://github.com/emmottlab/scpImaging 
 
<img width="1507" height="858" alt="Image" src="https://github.com/user-attachments/assets/00e4badc-aa37-4e9a-bef2-a2608bff15ee" />

**Comment by edemmott** [comment]
https://emmottlab.shinyapps.io/scpImaging_HEKA549/

**Comment by federicomarini** [comment]
Very nice work @edemmott !
Do you have the repo of this panel specifically somewhere? We are happy to link it among our "related resources" in some way 😉

**Comment by edemmott** [comment]
It forms part of this repo - rather than a standalone panel repo.
https://github.com/emmottlab/scpImaging

**Comment by edemmott** [comment]
The preprint covering this is now out: https://www.biorxiv.org/content/10.64898/2025.12.01.691577v1
